apiVersion: batch/v1
kind: CronJob
metadata:
  name: redeploy-apps
spec:
  schedule: "${REDEPLOY_JOB_SCHEDULE}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: redeployer
              image: ${OKTETO_BUILD_REDEPLOY_IMAGE}
              imagePullPolicy: IfNotPresent
              envFrom:
                - secretRef:
                    name: redeploy-secret
          restartPolicy: OnFailure